params:
  description: ""
  title: ""
  subtitle: ""
  author: ""
  formula: ""
  comparisons: ""
  contrast: ""
  input_file: ""
  design_file: ""
  FC_thr: 1
  adjpval_thr: 0.05
  Proteotypic: TRUE
  pep_per_prot: 3
  nNonZero: 30
  aggr_method: "medianPolish"
  normalization: "quantiles"
  filtering_contaminant: FALSE
  contaminant_str: ""
  folder_prj: ""
  ensembl_annotation: ""
  ensembl_col: ""
  confounder_list: ""
  PCA_comparison: "Group"
  quantitative_features: "Precursor.Quantity"
  filtPerGroup: ''
  mbr: FALSE
  wildstr_run: "CMB-"
  DIANN_ver2: FALSE
  keep_design_order: FALSE
  comparison_label: ""
  qf_obj: ""
